"""Knowledge base of Indian scam typologies ("playbooks").

Each playbook lists the behavioural signals (see satark/tools/signals.py) that
characterise it, with weights. `core` signals are required for a strong match.
Names and the one-line "truth" are localised (en / hi / te) so the agent can
explain the scam in the citizen's language even when running fully offline.
"""

from __future__ import annotations

PLAYBOOKS: list[dict] = [
    {
        "id": "digital_arrest",
        "name": {
            "en": "Digital arrest / fake police–CBI investigation",
            "hi": "डिजिटल अरेस्ट / नकली पुलिस–सीबीआई जांच",
            "te": "డిజిటల్ అరెస్ట్ / నకిలీ పోలీస్–సీబీఐ విచారణ",
        },
        "core": ["digital_arrest", "authority_impersonation"],
        "weights": {
            "digital_arrest": 0.55,
            "authority_impersonation": 0.35,
            "courier_parcel": 0.15,
            "secrecy": 0.25,
            "payment_request": 0.2,
            "video_call": 0.2,
            "urgency": 0.1,
        },
        "min_core": 1,
        "truth": {
            "en": "There is no 'digital arrest' in Indian law. Police, CBI, ED, Customs or RBI never question people on video calls or ask them to transfer money for 'verification'.",
            "hi": "भारतीय कानून में 'डिजिटल अरेस्ट' जैसा कुछ नहीं है। पुलिस, सीबीआई, ईडी, कस्टम या आरबीआई कभी वीडियो कॉल पर पूछताछ नहीं करते और न ही 'वेरिफिकेशन' के लिए पैसे ट्रांसफर करवाते हैं।",
            "te": "భారతీయ చట్టంలో 'డిజిటల్ అరెస్ట్' అనేది లేదు. పోలీసులు, సీబీఐ, ఈడీ, కస్టమ్స్ లేదా ఆర్‌బీఐ ఎప్పుడూ వీడియో కాల్‌లో విచారణ చేయరు, 'వెరిఫికేషన్' కోసం డబ్బు బదిలీ చేయమని అడగరు.",
        },
        "scammer_goal": "Keep the victim isolated on a video call under fear of arrest until they transfer savings to 'safe/verification' accounts (mule accounts).",
        "actions": ["disconnect_call", "stop_contact", "check_suspect", "report_chakshu", "warn_family"],
        "ncrp": ("Online Financial Fraud", "Fraud Call/Vishing"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Impersonation as Government official / relative",
        "critical": True,
    },
    {
        "id": "kyc_update",
        "name": {
            "en": "KYC / account-block phishing",
            "hi": "केवाईसी / खाता बंद होने का फ़िशिंग",
            "te": "కేవైసీ / ఖాతా బ్లాక్ ఫిషింగ్",
        },
        "core": ["kyc_threat"],
        "weights": {
            "kyc_threat": 0.45,
            "link_present": 0.2,
            "urgency": 0.15,
            "otp_request": 0.3,
            "apk_install": 0.3,
            "payment_request": 0.1,
        },
        "min_core": 1,
        "truth": {
            "en": "Banks never ask you to update KYC through SMS/WhatsApp links or apps sent by strangers. Indian bank websites now end in '.bank.in'.",
            "hi": "बैंक कभी भी SMS/WhatsApp लिंक या अनजान ऐप से केवाईसी अपडेट करने को नहीं कहते। भारतीय बैंकों की वेबसाइटें अब '.bank.in' पर खत्म होती हैं।",
            "te": "బ్యాంకులు ఎప్పుడూ SMS/WhatsApp లింక్‌లు లేదా తెలియని యాప్‌ల ద్వారా కేవైసీ అప్‌డేట్ చేయమని అడగవు. భారతీయ బ్యాంకుల వెబ్‌సైట్లు ఇప్పుడు '.bank.in' తో ముగుస్తాయి.",
        },
        "scammer_goal": "Harvest net-banking credentials, card details and OTPs on a look-alike page, or install a malicious app that forwards OTPs.",
        "actions": ["stop_contact", "verify_official", "never_share_otp", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Internet Banking Related Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Email Phishing"),
        "chakshu": "KYC update / expiry / deactivation related",
        "critical": False,
    },
    {
        "id": "malicious_apk",
        "name": {
            "en": "Malicious APK / remote-access takeover",
            "hi": "खतरनाक APK / रिमोट-एक्सेस से फ़ोन पर कब्ज़ा",
            "te": "ప్రమాదకర APK / రిమోట్ యాక్సెస్ ద్వారా ఫోన్ స్వాధీనం",
        },
        "core": ["apk_install", "remote_access"],
        "weights": {"apk_install": 0.6, "remote_access": 0.55, "link_present": 0.1, "urgency": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Banks, RTO, PM-Kisan or courier companies never send .apk files on WhatsApp/SMS. Such apps read your OTPs and give fraudsters control of your phone.",
            "hi": "बैंक, आरटीओ, पीएम-किसान या कूरियर कंपनियां कभी WhatsApp/SMS पर .apk फ़ाइल नहीं भेजतीं। ऐसे ऐप आपके OTP पढ़कर धोखेबाज़ों को फ़ोन का नियंत्रण दे देते हैं।",
            "te": "బ్యాంకులు, ఆర్టీఓ, పీఎం-కిసాన్ లేదా కొరియర్ సంస్థలు ఎప్పుడూ WhatsApp/SMS లో .apk ఫైళ్లు పంపవు. అలాంటి యాప్‌లు మీ OTP లను చదివి, మోసగాళ్లకు మీ ఫోన్‌పై నియంత్రణ ఇస్తాయి.",
        },
        "scammer_goal": "Get a remote-access tool or SMS-forwarding malware onto the phone, then drain bank accounts using intercepted OTPs.",
        "actions": ["uninstall_app", "call_bank_block", "stop_contact", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Internet Banking Related Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Profile Hacking/Identity Theft"),
        "chakshu": "Malicious links / website",
        "critical": True,
    },
    {
        "id": "echallan",
        "name": {"en": "Fake traffic e-challan", "hi": "नकली ट्रैफ़िक ई-चालान", "te": "నకిలీ ట్రాఫిక్ ఈ-చలాన్"},
        "core": ["challan"],
        "weights": {"challan": 0.45, "link_present": 0.2, "apk_install": 0.3, "payment_request": 0.15, "urgency": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Check and pay challans only on echallan.parivahan.gov.in or your state traffic police website — never through links received in SMS/WhatsApp.",
            "hi": "चालान केवल echallan.parivahan.gov.in या अपने राज्य की ट्रैफ़िक पुलिस वेबसाइट पर ही देखें और भरें — SMS/WhatsApp में आए लिंक से कभी नहीं।",
            "te": "చలాన్‌లను echallan.parivahan.gov.in లేదా మీ రాష్ట్ర ట్రాఫిక్ పోలీస్ వెబ్‌సైట్‌లో మాత్రమే చూసి చెల్లించండి — SMS/WhatsApp లో వచ్చిన లింక్‌ల ద్వారా ఎప్పుడూ కాదు.",
        },
        "scammer_goal": "Collect card/UPI details on a fake payment page or push an 'e-Challan' APK.",
        "actions": ["stop_contact", "verify_official", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Internet Banking Related Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Email Phishing"),
        "chakshu": "Malicious links / website",
        "critical": False,
    },
    {
        "id": "electricity_disconnection",
        "name": {
            "en": "Electricity disconnection threat",
            "hi": "बिजली कनेक्शन काटने की धमकी",
            "te": "కరెంట్ కనెక్షన్ కట్ చేస్తామనే బెదిరింపు",
        },
        "core": ["electricity_cut"],
        "weights": {"electricity_cut": 0.5, "urgency": 0.2, "remote_access": 0.25, "payment_request": 0.1, "apk_install": 0.25},
        "min_core": 1,
        "truth": {
            "en": "Electricity boards don't threaten same-night disconnection from personal mobile numbers. Pay only through your DISCOM's official app/website or Bharat BillPay apps.",
            "hi": "बिजली विभाग निजी मोबाइल नंबरों से उसी रात कनेक्शन काटने की धमकी नहीं देते। बिल केवल अपनी बिजली कंपनी के आधिकारिक ऐप/वेबसाइट या भारत बिलपे से ही भरें।",
            "te": "విద్యుత్ సంస్థలు వ్యక్తిగత మొబైల్ నంబర్ల నుండి అదే రాత్రి కనెక్షన్ కట్ చేస్తామని బెదిరించవు. బిల్లును మీ డిస్కమ్ అధికారిక యాప్/వెబ్‌సైట్ లేదా భారత్ బిల్‌పే ద్వారా మాత్రమే చెల్లించండి.",
        },
        "scammer_goal": "Panic the victim into calling an 'officer' who asks for a small payment via a screen-sharing app, then empties the account.",
        "actions": ["stop_contact", "verify_official", "uninstall_app", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Fraud Call/Vishing"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Bank account / payment wallet / SIM / gas / electricity connection related",
        "critical": False,
    },
    {
        "id": "task_job",
        "name": {
            "en": "Task-based part-time job scam",
            "hi": "टास्क-आधारित पार्ट-टाइम जॉब स्कैम",
            "te": "టాస్క్ ఆధారిత పార్ట్-టైమ్ ఉద్యోగ మోసం",
        },
        "core": ["job_task"],
        "weights": {"job_task": 0.5, "payment_request": 0.2, "telegram_whatsapp_move": 0.2, "reward_lure": 0.1, "urgency": 0.05},
        "min_core": 1,
        "truth": {
            "en": "Real employers never make you pay to unlock tasks or withdraw earnings. Small early payouts are bait for bigger 'prepaid tasks'.",
            "hi": "असली नौकरी देने वाले कभी टास्क खोलने या कमाई निकालने के लिए पैसे नहीं मांगते। शुरुआत की छोटी कमाई बड़े 'प्रीपेड टास्क' का चारा होती है।",
            "te": "నిజమైన యజమానులు టాస్క్‌లు అన్‌లాక్ చేయడానికి లేదా సంపాదన విత్‌డ్రా చేయడానికి ఎప్పుడూ డబ్బు అడగరు. మొదట్లో ఇచ్చే చిన్న మొత్తాలు పెద్ద 'ప్రీపెయిడ్ టాస్క్‌'లకు ఎర.",
        },
        "scammer_goal": "Build trust with tiny payouts, then demand ever-larger 'prepaid task' deposits that can never be withdrawn.",
        "actions": ["stop_contact", "check_suspect", "warn_family"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Online Job Fraud"),
        "chakshu": "Online job / lottery / gift / loan offer",
        "critical": False,
    },
    {
        "id": "investment_trading",
        "name": {
            "en": "Fake stock / IPO / crypto investment group",
            "hi": "नकली शेयर / आईपीओ / क्रिप्टो निवेश ग्रुप",
            "te": "నకిలీ షేర్ / ఐపీఓ / క్రిప్టో పెట్టుబడి గ్రూప్",
        },
        "core": ["investment_lure"],
        "weights": {"investment_lure": 0.5, "payment_request": 0.15, "telegram_whatsapp_move": 0.15, "urgency": 0.05, "reward_lure": 0.05},
        "min_core": 1,
        "truth": {
            "en": "No genuine adviser guarantees returns. Verify advisers on sebi.gov.in; fake trading apps show fake profits and then demand 'tax' or 'withdrawal fees'.",
            "hi": "कोई भी असली सलाहकार गारंटीड रिटर्न नहीं देता। सलाहकार की जांच sebi.gov.in पर करें; नकली ट्रेडिंग ऐप झूठा मुनाफ़ा दिखाकर 'टैक्स' या 'विदड्रॉल फ़ीस' मांगते हैं।",
            "te": "నిజమైన సలహాదారు ఎవరూ లాభాలకు గ్యారంటీ ఇవ్వరు. సలహాదారులను sebi.gov.in లో తనిఖీ చేయండి; నకిలీ ట్రేడింగ్ యాప్‌లు తప్పుడు లాభాలు చూపించి 'ట్యాక్స్' లేదా 'విత్‌డ్రాయల్ ఫీజు' అడుగుతాయి.",
        },
        "scammer_goal": "Lure victims into WhatsApp/Telegram 'VIP' groups and a fake trading app, show fake profits, then block withdrawals.",
        "actions": ["stop_contact", "verify_sebi", "check_suspect", "warn_family"],
        "ncrp": ("Online Financial Fraud", "Demat/Depository Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Investment / trading related",
        "critical": False,
    },
    {
        "id": "lottery_prize",
        "name": {"en": "Lottery / KBC / prize scam", "hi": "लॉटरी / केबीसी / इनाम स्कैम", "te": "లాటరీ / కేబీసీ / బహుమతి మోసం"},
        "core": ["reward_lure"],
        "weights": {"reward_lure": 0.45, "payment_request": 0.3, "urgency": 0.1, "link_present": 0.1},
        "min_core": 1,
        "truth": {
            "en": "You cannot win a lottery you never entered. No real prize asks for a 'processing fee' or tax payment to release it.",
            "hi": "जिस लॉटरी में आपने हिस्सा ही नहीं लिया, उसे आप जीत नहीं सकते। कोई भी असली इनाम 'प्रोसेसिंग फ़ीस' या टैक्स लेकर नहीं दिया जाता।",
            "te": "మీరు పాల్గొనని లాటరీని గెలవడం సాధ్యం కాదు. ఏ నిజమైన బహుమతి కోసం 'ప్రాసెసింగ్ ఫీజు' లేదా ట్యాక్స్ చెల్లించమని అడగరు.",
        },
        "scammer_goal": "Collect repeated 'processing', 'GST' or 'clearance' fees for a prize that does not exist.",
        "actions": ["stop_contact", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Online job / lottery / gift / loan offer",
        "critical": False,
    },
    {
        "id": "courier_customs_gift",
        "name": {
            "en": "Customs / courier / foreign-gift parcel scam",
            "hi": "कस्टम / कूरियर / विदेशी गिफ्ट पार्सल स्कैम",
            "te": "కస్టమ్స్ / కొరియర్ / విదేశీ గిఫ్ట్ పార్సెల్ మోసం",
        },
        "core": ["courier_parcel"],
        "weights": {"courier_parcel": 0.4, "payment_request": 0.25, "reward_lure": 0.15, "authority_impersonation": 0.15, "urgency": 0.1, "link_present": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Customs duty is never collected into personal bank accounts or UPI IDs, and courier companies don't threaten police action over parcels.",
            "hi": "कस्टम ड्यूटी कभी निजी बैंक खाते या UPI ID में नहीं ली जाती, और कूरियर कंपनियां पार्सल के नाम पर पुलिस कार्रवाई की धमकी नहीं देतीं।",
            "te": "కస్టమ్స్ డ్యూటీని ఎప్పుడూ వ్యక్తిగత బ్యాంక్ ఖాతాలు లేదా UPI IDల్లో వసూలు చేయరు; కొరియర్ సంస్థలు పార్సెల్ పేరుతో పోలీసు చర్యల బెదిరింపులు చేయవు.",
        },
        "scammer_goal": "Extract 'customs/clearance' payments, or escalate to a fake-police 'digital arrest'.",
        "actions": ["stop_contact", "verify_official", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Fraud Call/Vishing"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Impersonation as Government official / relative",
        "critical": False,
    },
    {
        "id": "upi_qr_receive",
        "name": {
            "en": "Scan-to-receive / UPI PIN trap",
            "hi": "'पैसे पाने के लिए स्कैन करें' / UPI पिन जाल",
            "te": "'డబ్బు పొందడానికి స్కాన్ చేయండి' / UPI పిన్ ఉచ్చు",
        },
        "core": ["pin_to_receive"],
        "weights": {"pin_to_receive": 0.65, "marketplace_buyer": 0.2, "payment_request": 0.1, "urgency": 0.05},
        "min_core": 1,
        "truth": {
            "en": "You never need to scan a QR code or enter your UPI PIN to RECEIVE money. The UPI PIN is only for sending money.",
            "hi": "पैसे प्राप्त करने के लिए कभी भी QR कोड स्कैन करने या UPI पिन डालने की ज़रूरत नहीं होती। UPI पिन केवल पैसे भेजने के लिए होता है।",
            "te": "డబ్బు పొందడానికి QR కోడ్ స్కాన్ చేయాల్సిన లేదా UPI పిన్ ఎంటర్ చేయాల్సిన అవసరం ఎప్పుడూ ఉండదు. UPI పిన్ డబ్బు పంపడానికి మాత్రమే.",
        },
        "scammer_goal": "Trick the victim into approving a payment (QR scan / PIN entry) while believing they are receiving money.",
        "actions": ["stop_contact", "never_share_otp", "check_suspect"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Bank account / payment wallet / SIM / gas / electricity connection related",
        "critical": True,
    },
    {
        "id": "refund_customer_care",
        "name": {
            "en": "Fake customer care / refund scam",
            "hi": "नकली कस्टमर केयर / रिफंड स्कैम",
            "te": "నకిలీ కస్టమర్ కేర్ / రీఫండ్ మోసం",
        },
        "core": ["refund_customer_care"],
        "weights": {"refund_customer_care": 0.4, "remote_access": 0.35, "otp_request": 0.3, "pin_to_receive": 0.3, "link_present": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Take helpline numbers only from the official app or website. Refunds never need your UPI PIN, OTP or screen-sharing.",
            "hi": "हेल्पलाइन नंबर केवल आधिकारिक ऐप या वेबसाइट से लें। रिफंड के लिए कभी भी UPI पिन, OTP या स्क्रीन-शेयरिंग की ज़रूरत नहीं होती।",
            "te": "హెల్ప్‌లైన్ నంబర్లను అధికారిక యాప్ లేదా వెబ్‌సైట్ నుండి మాత్రమే తీసుకోండి. రీఫండ్ కోసం UPI పిన్, OTP లేదా స్క్రీన్-షేరింగ్ ఎప్పుడూ అవసరం లేదు.",
        },
        "scammer_goal": "Pose as customer care (often via search-engine ads) and get screen-share access, OTPs or UPI PIN entry for a 'refund'.",
        "actions": ["stop_contact", "verify_official", "uninstall_app", "never_share_otp"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Fake customer care / helpline",
        "critical": False,
    },
    {
        "id": "relative_emergency",
        "name": {
            "en": "Family-emergency / voice-clone scam",
            "hi": "परिवार-आपातकाल / आवाज़-क्लोन स्कैम",
            "te": "కుటుంబ అత్యవసరం / వాయిస్-క్లోన్ మోసం",
        },
        "core": ["relative_emergency"],
        "weights": {"relative_emergency": 0.5, "urgency": 0.2, "payment_request": 0.2, "authority_impersonation": 0.1, "secrecy": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Fraudsters fake a relative's voice or 'new number'. Hang up and call your relative back on the number you already know.",
            "hi": "धोखेबाज़ रिश्तेदार की नकली आवाज़ या 'नया नंबर' इस्तेमाल करते हैं। फ़ोन काटें और रिश्तेदार को उनके पुराने, जाने-पहचाने नंबर पर खुद कॉल करें।",
            "te": "మోసగాళ్లు బంధువుల గొంతును లేదా 'కొత్త నంబర్'ను నకిలీ చేస్తారు. కాల్ కట్ చేసి, మీకు ముందే తెలిసిన నంబర్‌కు మీరే తిరిగి కాల్ చేయండి.",
        },
        "scammer_goal": "Exploit panic about a family member's arrest/accident to get an immediate transfer before the victim can verify.",
        "actions": ["call_relative_back", "stop_contact", "check_suspect", "warn_family"],
        "ncrp": ("Online Financial Fraud", "Fraud Call/Vishing"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Impersonation as Government official / relative",
        "critical": False,
    },
    {
        "id": "sim_swap_esim",
        "name": {"en": "SIM-swap / eSIM hijack", "hi": "सिम-स्वैप / ई-सिम हाईजैक", "te": "సిమ్-స్వాప్ / ఈ-సిమ్ హైజాక్"},
        "core": ["sim_swap"],
        "weights": {"sim_swap": 0.5, "otp_request": 0.35, "urgency": 0.1, "kyc_threat": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Telecom operators don't 'upgrade' SIMs over calls or ask for OTPs. An eSIM request you didn't make means someone is trying to take over your number.",
            "hi": "टेलीकॉम कंपनियां कॉल पर सिम 'अपग्रेड' नहीं करतीं और OTP नहीं मांगतीं। अगर आपने ई-सिम का अनुरोध नहीं किया, तो कोई आपका नंबर हथियाने की कोशिश कर रहा है।",
            "te": "టెలికాం సంస్థలు కాల్‌లో సిమ్‌ను 'అప్‌గ్రేడ్' చేయవు, OTP అడగవు. మీరు అడగని ఈ-సిమ్ అభ్యర్థన వస్తే, ఎవరో మీ నంబర్‌ను స్వాధీనం చేసుకోవడానికి ప్రయత్నిస్తున్నారు.",
        },
        "scammer_goal": "Take over the victim's mobile number to receive banking OTPs.",
        "actions": ["never_share_otp", "call_bank_block", "stop_contact", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Debit/Credit Card Fraud/Sim Swap Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Profile Hacking/Identity Theft"),
        "chakshu": "Bank account / payment wallet / SIM / gas / electricity connection related",
        "critical": False,
    },
    {
        "id": "loan_app",
        "name": {"en": "Fake / predatory loan app", "hi": "नकली / शोषक लोन ऐप", "te": "నకిలీ / దోపిడీ లోన్ యాప్"},
        "core": ["loan_lure", "loan_harassment"],
        "weights": {"loan_lure": 0.4, "loan_harassment": 0.45, "payment_request": 0.2, "apk_install": 0.2, "urgency": 0.05},
        "min_core": 1,
        "truth": {
            "en": "Genuine lenders (RBI-regulated banks/NBFCs) don't charge upfront fees to release a loan or threaten your contacts.",
            "hi": "असली ऋणदाता (RBI द्वारा विनियमित बैंक/NBFC) लोन देने से पहले फ़ीस नहीं लेते और आपके कॉन्टैक्ट्स को धमकाते नहीं।",
            "te": "నిజమైన రుణదాతలు (ఆర్‌బీఐ నియంత్రిత బ్యాంకులు/NBFCలు) లోన్ ఇవ్వడానికి ముందుగా ఫీజు వసూలు చేయరు, మీ కాంటాక్ట్‌లను బెదిరించరు.",
        },
        "scammer_goal": "Collect 'processing fees' for loans that never arrive, or harvest contacts/photos for extortion.",
        "actions": ["stop_contact", "uninstall_app", "check_suspect", "warn_family"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cyber Bullying/Stalking/Sexting"),
        "chakshu": "Online job / lottery / gift / loan offer",
        "critical": False,
    },
    {
        "id": "sextortion",
        "name": {"en": "Sextortion / video-call blackmail", "hi": "सेक्सटॉर्शन / वीडियो-कॉल ब्लैकमेल", "te": "సెక్స్‌టార్షన్ / వీడియో-కాల్ బ్లాక్‌మెయిల్"},
        "core": ["sextortion"],
        "weights": {"sextortion": 0.6, "payment_request": 0.2, "urgency": 0.1, "video_call": 0.1, "authority_impersonation": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Do not pay — paying only brings more demands. Preserve evidence, block the account and report it; you are the victim, not the offender.",
            "hi": "पैसे न दें — देने पर मांगें और बढ़ती हैं। सबूत संभालकर रखें, अकाउंट ब्लॉक करें और शिकायत करें; आप पीड़ित हैं, अपराधी नहीं।",
            "te": "డబ్బు చెల్లించవద్దు — చెల్లిస్తే డిమాండ్లు మరింత పెరుగుతాయి. సాక్ష్యాలను భద్రపరచండి, ఖాతాను బ్లాక్ చేసి ఫిర్యాదు చేయండి; మీరు బాధితులు, నేరస్థులు కాదు.",
        },
        "scammer_goal": "Extort repeated payments by threatening to leak recorded or morphed intimate content.",
        "actions": ["do_not_pay_sextortion", "preserve_evidence", "file_ncrp"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cyber Bullying/Stalking/Sexting"),
        "chakshu": "Sextortion",
        "critical": True,
    },
    {
        "id": "mule_recruitment",
        "name": {
            "en": "Money-mule recruitment (renting your bank account)",
            "hi": "मनी-म्यूल भर्ती (बैंक खाता किराए पर देना)",
            "te": "మనీ-మ్యూల్ నియామకం (బ్యాంక్ ఖాతాను అద్దెకు ఇవ్వడం)",
        },
        "core": ["mule_recruit"],
        "weights": {"mule_recruit": 0.6, "job_task": 0.15, "payment_request": 0.05, "telegram_whatsapp_move": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Letting anyone use your bank account, UPI or SIM for 'commission' makes you legally liable; such accounts get frozen and reported.",
            "hi": "'कमीशन' के लिए किसी को अपना बैंक खाता, UPI या सिम इस्तेमाल करने देना आपको कानूनी रूप से ज़िम्मेदार बनाता है; ऐसे खाते फ़्रीज़ और रिपोर्ट किए जाते हैं।",
            "te": "'కమీషన్' కోసం మీ బ్యాంక్ ఖాతా, UPI లేదా సిమ్‌ను ఇతరులు వాడుకునేలా చేస్తే మీరు చట్టపరంగా బాధ్యులవుతారు; అలాంటి ఖాతాలు ఫ్రీజ్ చేయబడి, నివేదించబడతాయి.",
        },
        "scammer_goal": "Recruit people (often students) to receive and forward stolen money so the real fraudsters stay hidden.",
        "actions": ["stop_mule", "stop_contact", "check_suspect"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Online Job Fraud"),
        "chakshu": "Online job / lottery / gift / loan offer",
        "critical": True,
    },
    {
        "id": "wrong_transfer",
        "name": {
            "en": "'Sent by mistake, please return' scam",
            "hi": "'गलती से पैसे भेज दिए, लौटा दो' स्कैम",
            "te": "'పొరపాటున డబ్బు పంపాను, తిరిగి ఇవ్వండి' మోసం",
        },
        "core": ["wrong_transfer"],
        "weights": {"wrong_transfer": 0.5, "payment_request": 0.2, "urgency": 0.1},
        "min_core": 1,
        "truth": {
            "en": "Check your balance in your official bank app, not the SMS. If money was truly credited by mistake, the sender's bank will reverse it — never send money yourself.",
            "hi": "SMS नहीं, अपने बैंक के आधिकारिक ऐप में बैलेंस देखें। अगर सच में गलती से पैसा आया है, तो भेजने वाले का बैंक उसे वापस करेगा — आप खुद पैसे न भेजें।",
            "te": "SMS కాదు, మీ అధికారిక బ్యాంక్ యాప్‌లో బ్యాలెన్స్ చూసుకోండి. నిజంగా పొరపాటున డబ్బు వచ్చి ఉంటే, పంపిన వారి బ్యాంక్ దాన్ని వెనక్కి తీసుకుంటుంది — మీరే డబ్బు పంపవద్దు.",
        },
        "scammer_goal": "Send a fake 'credited' SMS and pressure the victim into 'returning' money that never arrived.",
        "actions": ["verify_official", "stop_contact", "check_suspect"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Bank account / payment wallet / SIM / gas / electricity connection related",
        "critical": False,
    },
    {
        "id": "fake_govt_scheme",
        "name": {"en": "Fake government scheme / subsidy", "hi": "नकली सरकारी योजना / सब्सिडी", "te": "నకిలీ ప్రభుత్వ పథకం / సబ్సిడీ"},
        "core": ["govt_scheme_fee"],
        "weights": {"govt_scheme_fee": 0.4, "payment_request": 0.25, "link_present": 0.15, "apk_install": 0.25, "reward_lure": 0.1, "urgency": 0.05},
        "min_core": 1,
        "truth": {
            "en": "Government schemes don't collect registration fees over UPI. Verify on myscheme.gov.in or the scheme's official .gov.in portal.",
            "hi": "सरकारी योजनाएं UPI पर रजिस्ट्रेशन फ़ीस नहीं लेतीं। myscheme.gov.in या योजना के आधिकारिक .gov.in पोर्टल पर जांच करें।",
            "te": "ప్రభుత్వ పథకాలు UPI ద్వారా రిజిస్ట్రేషన్ ఫీజు వసూలు చేయవు. myscheme.gov.in లేదా పథకం యొక్క అధికారిక .gov.in పోర్టల్‌లో తనిఖీ చేయండి.",
        },
        "scammer_goal": "Collect 'registration' fees or Aadhaar/bank details using the name of a real welfare scheme.",
        "actions": ["stop_contact", "verify_official", "check_suspect", "warn_family"],
        "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Online job / lottery / gift / loan offer",
        "critical": False,
    },
    {
        "id": "tax_refund",
        "name": {"en": "Income-tax / GST refund phishing", "hi": "आयकर / जीएसटी रिफंड फ़िशिंग", "te": "ఆదాయపు పన్ను / జీఎస్టీ రీఫండ్ ఫిషింగ్"},
        "core": ["tax_refund"],
        "weights": {"tax_refund": 0.45, "link_present": 0.25, "otp_request": 0.2, "kyc_threat": 0.1, "urgency": 0.05},
        "min_core": 1,
        "truth": {
            "en": "Tax refunds are credited automatically to your validated bank account. The department doesn't send refund links — check status on incometax.gov.in.",
            "hi": "टैक्स रिफंड अपने-आप आपके सत्यापित बैंक खाते में आता है। विभाग रिफंड के लिंक नहीं भेजता — स्थिति incometax.gov.in पर देखें।",
            "te": "పన్ను రీఫండ్ మీ ధృవీకరించిన బ్యాంక్ ఖాతాలో ఆటోమేటిక్‌గా జమ అవుతుంది. శాఖ రీఫండ్ లింక్‌లు పంపదు — స్థితిని incometax.gov.in లో చూడండి.",
        },
        "scammer_goal": "Harvest bank login and card details on a fake 'refund' page.",
        "actions": ["stop_contact", "verify_official", "check_suspect", "report_chakshu"],
        "ncrp": ("Online Financial Fraud", "Internet Banking Related Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Email Phishing"),
        "chakshu": "Malicious links / website",
        "critical": False,
    },
    {
        "id": "pension_life_cert",
        "name": {"en": "Pension / life-certificate scam", "hi": "पेंशन / जीवन प्रमाण-पत्र स्कैम", "te": "పెన్షన్ / లైఫ్ సర్టిఫికేట్ మోసం"},
        "core": ["pension_life_cert"],
        "weights": {"pension_life_cert": 0.35, "otp_request": 0.35, "link_present": 0.15, "urgency": 0.1, "kyc_threat": 0.15},
        "min_core": 1,
        "truth": {
            "en": "Life certificates are submitted via Jeevan Pramaan, your bank branch or doorstep banking. No official calls to ask for OTPs or fees.",
            "hi": "जीवन प्रमाण-पत्र जीवन प्रमाण पोर्टल, बैंक शाखा या डोरस्टेप बैंकिंग से जमा होता है। कोई अधिकारी OTP या फ़ीस मांगने के लिए फ़ोन नहीं करता।",
            "te": "లైఫ్ సర్టిఫికేట్‌ను జీవన్ ప్రమాణ్, మీ బ్యాంక్ శాఖ లేదా డోర్‌స్టెప్ బ్యాంకింగ్ ద్వారా సమర్పిస్తారు. OTP లేదా ఫీజు కోసం ఏ అధికారీ కాల్ చేయరు.",
        },
        "scammer_goal": "Scare pensioners about stopped pensions to obtain OTPs or bank details.",
        "actions": ["never_share_otp", "verify_official", "stop_contact", "warn_family"],
        "ncrp": ("Online Financial Fraud", "Fraud Call/Vishing"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
        "chakshu": "Impersonation as Government official / relative",
        "critical": False,
    },
    {
        "id": "card_reward",
        "name": {
            "en": "Credit-card reward / limit-increase phishing",
            "hi": "क्रेडिट कार्ड रिवॉर्ड / लिमिट बढ़ाने का फ़िशिंग",
            "te": "క్రెడిట్ కార్డ్ రివార్డ్ / లిమిట్ పెంపు ఫిషింగ్",
        },
        "core": ["card_reward"],
        "weights": {"card_reward": 0.45, "link_present": 0.2, "otp_request": 0.3, "urgency": 0.1, "apk_install": 0.2},
        "min_core": 1,
        "truth": {
            "en": "Redeem reward points or change card limits only inside your bank's official app or website — never through SMS links or callers.",
            "hi": "रिवॉर्ड पॉइंट रिडीम करना या कार्ड लिमिट बदलना केवल बैंक के आधिकारिक ऐप या वेबसाइट में करें — SMS लिंक या कॉल करने वालों के ज़रिए कभी नहीं।",
            "te": "రివార్డ్ పాయింట్లు రిడీమ్ చేయడం లేదా కార్డ్ లిమిట్ మార్చడం మీ బ్యాంక్ అధికారిక యాప్ లేదా వెబ్‌సైట్‌లో మాత్రమే చేయండి — SMS లింక్‌లు లేదా కాలర్ల ద్వారా ఎప్పుడూ కాదు.",
        },
        "scammer_goal": "Capture card number, CVV and OTP on a fake 'redeem points' page.",
        "actions": ["stop_contact", "verify_official", "never_share_otp", "check_suspect"],
        "ncrp": ("Online Financial Fraud", "Debit/Credit Card Fraud/Sim Swap Fraud"),
        "ncrp_nonfin": ("Online and Social Media Related Crime", "Email Phishing"),
        "chakshu": "Malicious links / website",
        "critical": False,
    },
]

GENERIC = {
    "id": "generic_suspicious",
    "name": {"en": "Suspicious communication", "hi": "संदिग्ध संदेश/कॉल", "te": "అనుమానాస్పద సందేశం/కాల్"},
    "truth": {
        "en": "When in doubt, stop. Verify through the official app or website you already use, and never share OTP, PIN or passwords.",
        "hi": "शक हो तो रुकें। केवल उसी आधिकारिक ऐप या वेबसाइट से जांच करें जिसे आप पहले से इस्तेमाल करते हैं, और OTP, पिन या पासवर्ड कभी न बताएं।",
        "te": "అనుమానం ఉంటే ఆగండి. మీరు ఇప్పటికే వాడుతున్న అధికారిక యాప్ లేదా వెబ్‌సైట్ ద్వారానే తనిఖీ చేయండి; OTP, పిన్ లేదా పాస్‌వర్డ్‌లను ఎప్పుడూ చెప్పవద్దు.",
    },
    "scammer_goal": "Unclear — treat any request for money, OTP/PIN, app installs or secrecy as a red flag.",
    "actions": ["stop_contact", "verify_official", "never_share_otp", "check_suspect"],
    "ncrp": ("Online Financial Fraud", "UPI Related Frauds"),
    "ncrp_nonfin": ("Online and Social Media Related Crime", "Cheating by Impersonation"),
    "chakshu": "Others",
    "critical": False,
}

PLAYBOOK_BY_ID: dict[str, dict] = {p["id"]: p for p in PLAYBOOKS}
PLAYBOOK_BY_ID[GENERIC["id"]] = GENERIC


def get_playbook(pid: str | None) -> dict:
    return PLAYBOOK_BY_ID.get(pid or "", GENERIC)
